defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs
  output_subdir: ./configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: log_${now:%Y-%m-%d}_${now:%H-%M-%S}

runs:
  dev: False
  resume: False
  evaluate: False
  logger: 'tensorboard'
  gpu_id: '0'
  precision: 32

dataset:
  image_dir: '/mnt/nfs/kuroyanagi/clones/PyTorch-Lightning-CIFAR10/data'

train:
  classifier: 'resnet18'
  num_epochs: 2
  batch_size: 512
  num_workers: 4
  learning_rate: 1e-2
  weight_decay: 1e-2
  checkpoint_model: ''
  checkpoint_interval: 5
  checkpoints_dir: 'checkpoints'
  tensorboard_dir: 'logs'

test:
  num_classes: 10
  batch_size: 512
  checkpoint_model: ''
