defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs
  output_subdir: ./configs/${now:%Y-%m-%d}/${now:%H-%M-%S}

runs:
  dev: False
  evaluate: False
  logger: 'tensorboard'
  gpu_id: '0'
  precision: 32

dataset:
  image_dir: '/mnt/nfs/kuroyanagi/clones/PyTorch-Lightning-CIFAR10/data'

model:
  classifier: 'resnet18'
  implementation: 'timm'
  pretrained: True

transform:
  normalization: 'imagenet'

train:
  num_classes: 10
  num_epochs: 10
  batch_size: 512
  num_workers: 4
  learning_rate: 1e-2
  weight_decay: 1e-2
  tensorboard_dir: 'logs'
  checkpoint: null

test:
  batch_size: 512
  checkpoint_model: ''
