defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs
  output_subdir: ./configs/${now:%Y-%m-%d}/${now:%H-%M-%S}

runs:
  dev: False
  evaluate: False
  # Specify 'tensorboard' or 'wandb'.
  logger: 'tensorboard'
  gpu_id: '0'
  precision: 32

dataset:
  # Do not specify AWS EFS. Please specify AWS EBS.
  root_dir: '/home/anasys/datasets'
  # Specify 'custom' when loading as a custom dataset. By default, load by torchvision is performed.
  loading: 'torchvision'

model:
  classifier: 'resnet18'
  # Specify 'scratch' or 'timm'.
  implementation: 'scratch'
  # Specifies whether to use the pretrained model with timm.
  pretrained: True

transform:
  # Specify 'cidar10' in the scratch implementation of resnet, and specify 'imagenet' when using the pretrained model of timm.
  normalization: 'cifar10'

train:
  num_classes: 10
  num_epochs: 200
  batch_size: 512
  num_workers: 4
  learning_rate: 1e-2
  weight_decay: 1e-2
  tensorboard_dir: 'logs'
  checkpoint: null

test:
  batch_size: 512
  hparams: './outputs/train_exp01/logs/resnet18/version_0/hparams.yaml'
  checkpoint: "./outputs/train_exp01/logs/resnet18/version_0/checkpoints/'epoch=198-step=19302.ckpt'"
